config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :users
  resources :shops
  resources :services
  resources :appointments
  resources :schedules
  resources :charges, only: [:new, :create]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user, optional: true, dependent: :destroy
  belongs_to :shop, optional: true, dependent: :destroy
  belongs_to :service, optional: true
  belongs_to :schedule, optional: true

  validates :start_at, presence: true
  validates :user_id, presence: true
  validates :shop_id, presence: true

  def start_time
    self.start_date
  end

  # resourcify
end

app/models/client.rb
class Client < ApplicationRecord

  before_save {self.email = email.downcase}

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  has_secure_password
  validates :password, presence: true, length: {minimum: 4}

  has_many :appointments, dependent: :destroy
  has_many :schedules
  belongs_to :shop, optional: true

  def full_name
    self.first_name + ' ' + self.last_name
  end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles

belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  has_many :appointments

  validates :start_at, presence: true
  validates :end_at, presence: true

end

app/models/service.rb
class Service < ApplicationRecord
  has_many :appointments

  # resourcify 

  def service_price
    self.name + ' ' + '$' + self.price.to_s
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :appointments
  has_many :users

  validates :name, presence: true
  validates :address, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  rolify

  before_save {self.email = email.downcase}

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  has_secure_password
  validates :password, presence: true, length: {minimum: 4}

  has_many :appointments, dependent: :destroy
  has_many :schedules
  belongs_to :shop, optional: true

  def full_name
    self.first_name + ' ' + self.last_name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:edit, :show, :update]

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    if @service.valid?
       @service.save
       flash[:success] = "#{@service.name} added to list of services!"
       redirect_to @service
    else
       render 'services/new'
    end
  end

  def show
  end

  def edit
  end

  def index
    @services = Service.all
  end

  def destroy
    @service = Service.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  private
  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:name, :price)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:edit, :show, :update]
  before_action :set_shops, only: [:show]

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.valid?
       @shop.save
       flash[:notice] = "#{@shop.name} created!"
       redirect_to shops_path
    else
       render 'shops/new'
    end
  end

  def show
    @services = Service.all
    @appt = Appointment.new
    @appts = Appointment.all
  end

  def edit
  end

  def update
    @shop.update(shop_params)
    redirect_to shops_path(@shop)
  end

  def index
    @shops = Shop.all
  end

  def destroy
    @shop = User.find(params[:id])
    respond_to do |format|
      format.js
    end
    # @shop.destroy
    redirect_to root_path
  end

  private
  def set_shop
    @shop = Shop.find(params[:id])
  end

  def set_shops
    @shops = Shop.all
  end

  def shop_params
    params.require(:shop).permit(:name,
                                 :address,
                                 :phone,
                                 :hours)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
       @user.save
       log_in @user
       flash[:success] = "Welcome to Barbershop+!"
       redirect_to @user
    else
      redirect_to new_user_path
    end
  end

  def show
    @appts = Appointment.all
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to users_path(@user)
  end

  def index
    @user = User.all
  end

  def destroy
    @user = User.find(params[:id])
    respond_to do |format|
      format.js
    end
    # @user.destroy
    redirect_to root_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :shop_id,
                                 {role_ids: []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name
    self.first_name + '' + self.last_name
  end
end

app/views/services/_index.html.erb
<div class="table-responsive-sm">
  <table class="table services">

    <caption class="service-header">Services</caption>
    <% if current_user.has_any_role?(:admin, :barber) %>
    <caption class="add-service">
      <%= link_to new_service_path do %>
        <i class="fas fa-plus-circle"></i>
      <% end %>
    </caption>
    <thead>
      <tr>
        <th scope="col">Type</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
      <% @services.each do |s| %>
      <tr>
        <td><%= s.name.capitalize %></td>
        <td>$<%= s.price %></td>
      </tr>
      <% end %>
     <% end %>
    </tbody>
  </table>
</div>

app/views/services/edit.html.erb
<h1>Services#edit</h1>
<p>Find me in app/views/services/edit.html.erb</p>

app/views/services/index.html.erb
<div class="table-responsive-sm">
  <table class="table services">

    <caption class="service-header">Services</caption>
    <% if current_user.has_any_role?(:admin, :barber) %>
    <caption class="add-service">
      <%= link_to new_service_path do %>
        <i class="fas fa-plus-circle"></i>
      <% end %>
    </caption>
    <thead>
      <tr>
        <th scope="col">Type</th>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
      <% @services.each do |s| %>
      <tr>
        <td><%= s.name.capitalize %></td>
        <td>$<%= s.price %></td>
      </tr>
      <% end %>
     <% end %>
    </tbody>
  </table>
</div>

app/views/services/new.html.erb
<% if current_user.has_any_role?(:admin, :barber) %>
<h1>Add new service</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@service) do |f| %>

    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :price %><br>
    <%= f.text_field :price %><br>

    <%= f.submit 'Submit', class: "btn btn-primary" %>
  <% end %>
  </div>
</div>
<% end %>

app/views/services/show.html.erb
<%= link_to "Back to Barbershop", shop_path, class:"back-btn" %>