config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :users
  resources :shops
  resources :services
  resources :appointments
  resources :schedules
  resources :charges, only: [:new, :create]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user, optional: true, dependent: :destroy
  belongs_to :shop, optional: true, dependent: :destroy
  belongs_to :service, optional: true
  belongs_to :schedule, optional: true

  validates :start_at, presence: true
  validates :user_id, presence: true
  validates :shop_id, presence: true

  def start_time
    self.start_date
  end

  # resourcify
end

app/models/client.rb
class Client < ApplicationRecord

  before_save {self.email = email.downcase}

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  has_secure_password
  validates :password, presence: true, length: {minimum: 4}

  has_many :appointments, dependent: :destroy
  has_many :schedules
  belongs_to :shop, optional: true

  def full_name
    self.first_name + ' ' + self.last_name
  end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles

belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  has_many :appointments

  validates :start_at, presence: true
  validates :end_at, presence: true

end

app/models/service.rb
class Service < ApplicationRecord
  has_many :appointments

  # resourcify 

  def service_price
    self.name + ' ' + '$' + self.price.to_s
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :appointments
  has_many :users

  validates :name, presence: true
  validates :address, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  rolify

  before_save {self.email = email.downcase}

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  has_secure_password
  validates :password, presence: true, length: {minimum: 4}

  has_many :appointments, dependent: :destroy
  has_many :schedules
  belongs_to :shop, optional: true

  def full_name
    self.first_name + ' ' + self.last_name
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_appointment_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:edit, :show, :update]
  before_action :set_shops, only: [:show]

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.valid?
       @shop.save
       flash[:notice] = "#{@shop.name} created!"
       redirect_to shops_path
    else
       render 'shops/new'
    end
  end

  def show
    @services = Service.all
    @appt = Appointment.new
    @appts = Appointment.all
  end

  def edit
  end

  def update
    @shop.update(shop_params)
    redirect_to shops_path(@shop)
  end

  def index
    @shops = Shop.all
  end

  def destroy
    @shop = User.find(params[:id])
    respond_to do |format|
      format.js
    end
    # @shop.destroy
    redirect_to root_path
  end

  private
  def set_shop
    @shop = Shop.find(params[:id])
  end

  def set_shops
    @shops = Shop.all
  end

  def shop_params
    params.require(:shop).permit(:name,
                                 :address,
                                 :phone,
                                 :hours)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :show, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
       @user.save
       log_in @user
       flash[:success] = "Welcome to Barbershop+!"
       redirect_to @user
    else
      redirect_to new_user_path
    end
  end

  def show
    @appts = Appointment.all
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to users_path(@user)
  end

  def index
    @user = User.all
  end

  def destroy
    @user = User.find(params[:id])
    respond_to do |format|
      format.js
    end
    # @user.destroy
    redirect_to root_path
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :shop_id,
                                 {role_ids: []})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name
    self.first_name + '' + self.last_name
  end
end

app/views/shops/destroy.js.erb
console.log('testing');

app/views/shops/edit.html.erb
<h1>Edit Shop</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@shop) do |f| %>

    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :address %><br>
    <%= f.text_field :address %><br>
    <%= f.label :phone %><br>
    <%= f.telephone_field :phone %><br>
    <%= f.label :hours %><br>
    <%= f.text_field :hours %><br>

    <%= f.submit 'Save Changes', class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/shops/index.html.erb
<table class="table table-striped">
  <caption class="barbershop-header">Barbershops</caption>
  <% if current_user.has_any_role?(:barber) %>
  <caption class="add-service">
    <%= link_to new_shop_path do %>
      <i class="fas fa-plus-circle"></i>
    <% end %>
  </caption>
  <% end %>
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Phone</th>
      <th scope="col">Hours</th>
      <th scope="col">Profile</th>
    </tr>
  </thead>
  <tbody>
    <% @shops.each do |s| %>
    <tr>
      <td><%= s.name.capitalize %></td>
      <td><%= s.address %></td>
      <td><%= s.phone %></td>
      <td><%= s.hours %></td>
      <% if logged_in? %>
      <td>
        <%= link_to shop_path(s.id) do %>
          <i class="fas fa-home"></i>
        <% end %>
      </td>
      <% else %>
        <td>Log in for access to barbershop profile</td>
      <% end %>
    <% end %>
    </tr>
  </tbody>
</table>

app/views/shops/new.html.erb
<h1>Register a Barbershop</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <%= form_for(@shop) do |f| %>

    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :address %><br>
    <%= f.text_field :address %><br>
    <%= f.label :phone %><br>
    <%= f.telephone_field :phone %><br>
    <%= f.label :hours %><br>
    <%= f.text_field :hours %><br>

    <%= f.submit 'Register', class: "btn btn-primary" %>
  <% end %>
  </div>
</div>

app/views/shops/show.html.erb
<div class="main-container">
  <div>
    <ul class="shop-info">
      <li>Name: <%= @shop.name.capitalize %></li>
      <li>Address: <%= @shop.address %></li>
      <li>Tele: <%= @shop.phone %></li>
    </ul>
  </div>

  <section>
    <%= link_to "Edit Appt", edit_appointment_path, class:"edit-appt" %>
    <button class="open-sidebar" onclick="openSidebar()">Book Appointment</button>
    <%= render 'appointments/new' %>
    <%= link_to "Edit Shop", edit_shop_path, class:"edit-shop" %>
    <%= link_to "Delete Shop", @shop, method: :delete, remote: true, class:"delete-shop", data: {confirm: "are you sure?"} %>
  </section>

  <section>
    <%= month_calendar events: @appts do |date, appts| %>
      <%= date.day %>
      <% if @appts.present? %>
      <% appts.each do |a| %>
       <div>
         <span>@<%= a.start_at.strftime("%H:%M") %></span>
         <span>| Barber: <%= a.user.first_name.capitalize %></span>
       </div>
      <% end %>
     <% end %>
    <% end %>
  </section>

  <div class="table-responsive-sm">
    <table class="table barbers">
      <caption class="barber-header">Barbers</caption>
      <% if current_user.has_any_role?(:barber) %>
      <caption class="add-barber">
        <%= link_to new_user_path do %>
          <i class="fas fa-plus-circle"></i>
        <% end %>
      </caption>
      <% end %>
      <thead>
        <tr>
          <th scope="col">First Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Profile</th>
        </tr>
      </thead>
      <tbody>
        <% @shop.users.each do |u| %>
        <tr>
          <td><%= u.first_name.capitalize %></td>
          <td><%= u.last_name.capitalize %></td>
          <td><%= link_to "Profile", user_path(u.id) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<%= render 'services/index' %>

app/views/users/destroy.js.erb
console.log("testing");

app/views/users/edit.html.erb
<h1>Edit</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= f.label :first_name, 'First Name' %><br>
    <%= f.text_field :first_name %><br>
    <%= f.label :last_name, 'Last Name' %><br>
    <%= f.text_field :last_name %><br>
    <%= f.label :email %><br>
    <%= f.email_field :email %><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
      <% for role in Role.all %>
        <div>
          <%= radio_button_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
          <%= role.name.capitalize %>
        </div>
      <% end %>
    <%= f.collection_select :shop_id, Shop.all, :id, :name, {include_blank: true } %><br>
    <%= f.submit 'Save Changes', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%= f.label :first_name, 'First Name' %><br>
    <%= f.text_field :first_name %><br>
    <%= f.label :last_name, 'Last Name' %><br>
    <%= f.text_field :last_name %><br>
    <%= f.label :email %><br>
    <%= f.email_field :email %><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
      <% for role in Role.all %>
        <div>
          <%= radio_button_tag "user[role_ids][]", role.id, @user.roles.include?(role) %>
          <%= role.name.capitalize %>
        </div>
      <% end %>
    <%= f.collection_select :shop_id, Shop.all, :id, :name, {include_blank: true } %><br>
    <%= f.submit 'Create', class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div>
  <ul class="user-info">
    <li>Profile Name: <%= @user.first_name.capitalize %></li>
    <li>Email: <%= @user.email %></li>
  </ul>
</div>

<div>
    <%= link_to "Edit User", edit_user_path, class:"edit-user" %>
  <% if current_user.has_any_role?(:barber) %>
    <%= link_to "Add Schedule", new_schedule_path, class:"edit-user" %>
  <% end %>
    <%= link_to "Delete User", @user, method: :delete, remote: true, class:"delete-user", data: {confirm: "are you sure?"} %>
</div>

<section>
  <% if current_user.has_any_role?(:client) %>
  <%= month_calendar events: @appts do |date, appts| %>
    <%= date.day %>
    <% if @appts.present? %>
    <% appts.each do |a| %>
     <div>
       <span>@<%= a.start_at.strftime("%H:%M") %></span>
       <span>| Barber: <%= a.user.first_name.capitalize %></span>
     </div>
    <% end %>
   <% end %>
  <% end %>
</section>

<section>
  <% elsif current_user.has_any_role?(:barber) %>
  <% if @user.appointments.present? %>
  <table class="table table-striped">
    <caption class="appointment-header">Appointment Schedule</caption>
    <thead>
      <tr>
        <th scope="col">Barbershop</th>
        <th scope="col">Location</th>
        <th scope="col">Client</th>
        <th scope="col">Time of Appointment</th>
      </tr>
    </thead>
    <tbody>
      <% @user.appointments.each do |u| %>
      <tr>
        <td><%= u.shop.name.capitalize %></td>
        <td><%= u.shop.address %></td>
        <td><%= u.user.first_name.capitalize %></td>
        <td><%= u.start_at.strftime("%H:%M") %></td>
      <% end %>
      </tr>
    </tbody>
  </table>
  <% else %>
  <h1 class="profile-header">No Appointments Scheduled</h1>
  <% end %>
</section>

<!-- barber schedule -->
<section>
    <table class="table table-striped-barber">
      <caption class="schedule-header">Work Schedule</caption>
      <thead>
        <tr>
          <th scope="col">Status</th>
          <th scope="col">Start Time</th>
          <th scope="col">End Time</th>
        </tr>
      </thead>
      <tbody>
        <% @user.schedules.each do |u| %>
        <tr>
          <td><%= u.status.capitalize %></td>
          <td><%= u.start_at.strftime("%H:%M") %></td>
          <td><%= u.end_at.strftime("%H:%M") %></td>
        <% end %>
        </tr>
      </tbody>
    </table>
</section>
<% end %>