config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :users
  resources :shops
  resources :services
  resources :appointments
  resources :schedules
  resources :charges, only: [:new, :create]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user, optional: true, dependent: :destroy
  belongs_to :shop, optional: true, dependent: :destroy
  belongs_to :service, optional: true
  belongs_to :schedule, optional: true

  validates :start_at, presence: true
  validates :user_id, presence: true
  validates :shop_id, presence: true

  def start_time
    self.start_date
  end

  # resourcify
end

app/models/client.rb
class Client < ApplicationRecord

  before_save {self.email = email.downcase}

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  has_secure_password
  validates :password, presence: true, length: {minimum: 4}

  has_many :appointments, dependent: :destroy
  has_many :schedules
  belongs_to :shop, optional: true

  def full_name
    self.first_name + ' ' + self.last_name
  end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles

belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  has_many :appointments

  validates :start_at, presence: true
  validates :end_at, presence: true

end

app/models/service.rb
class Service < ApplicationRecord
  has_many :appointments

  # resourcify 

  def service_price
    self.name + ' ' + '$' + self.price.to_s
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :appointments
  has_many :users

  validates :name, presence: true
  validates :address, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  rolify

  before_save {self.email = email.downcase}

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  has_secure_password
  validates :password, presence: true, length: {minimum: 4}

  has_many :appointments, dependent: :destroy
  has_many :schedules
  belongs_to :shop, optional: true

  def full_name
    self.first_name + ' ' + self.last_name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def full_name
    self.first_name + '' + self.last_name
  end
end

app/views/layouts/_navbar.html.erb
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

<ul class="nav">
  <% if current_user %>
    <li class="nav-item"><%= link_to "Logout", logout_path, method: :delete, class:"nav-link" %></li>
    <li class="nav-item"><%= link_to "Profile", user_path(@current_user), class:"nav-link active" %></li>
    <li class="nav-item"><%= link_to "Barbershops", shops_path, class:"nav-link" %></li>
  <% else %>
    <li class="nav-item"><%= link_to "Sign Up", new_user_path, class:"nav-link" %></li>
    <li class="nav-item"><%= link_to "Login", login_path, class:"nav-link" %></li>
  <% end %>
    <li class="nav-item"><%= link_to "Home", root_path, class:"nav-link" %></li>
    <li id="logo" class="nav-item"><img src="/assets/logo2.png" class="nav-link" alt="barbershop+"></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barbershop+</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <%= render 'layouts/navbar' %>
  </head>

  <body>
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<body id="home">

  <div class="container">
    <h1>Features</h1>
    <hr>
    <div class="row">
      <div class="col-md-5 feat-barber">
        <h2>Barbers</h2>
        <ul>
          <li>Register Your Barbershop</li>
          <li>Manage Clientele & Employees</li>
          <li>Grow Your Business</li>
        </ul>
      </div>
      <div class="col-md-4 feat-client">
        <h2>Clients</h2>
        <ul>
          <li>Search Barbershops</li>
          <li>Book Appointments</li>
          <li>Pay Online</li>
        </ul>
      </div>
    </div>
  </div>

</body>